name: CI - Test Build Health-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies & pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run tests (pytest)
        run: pytest -q

      - name: Build Docker image
        run: docker build -t ci-web .

      - name: Run container and health-check
        run: |
          docker run -d --name ci-web -p 5000:5000 ci-web
          # give app a moment
          sleep 2
          # fail if health endpoint not ok (robust JSON check)
          curl -s http://localhost:5000/health | python -c "import sys,json; j=json.load(sys.stdin); assert j.get('status')=='ok'"
        
      - name: Stop & remove container
        if: always()
        run: |
          docker stop ci-web || true
          docker rm ci-web   || true
