name: CI

on: [push, pull_request]

jobs:
  test-and-health:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t ci-web .

      - name: Run container and check /health
        run: |
          docker run -d --name ci-web -p 5000:5000 ci-web
          # small wait for server to start
          sleep 2
          curl -f http://localhost:5000/health

      - name: Cleanup container
        if: always()
        run: |
          docker stop ci-web || true
          docker rm ci-web || true
