name: Run Script 

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     

      - name: Run Python script
        run: python app.py
